# Generated by Django 5.0.1 on 2024-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('qual', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
