# Generated by Django 4.2.7 on 2023-11-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_title', models.CharField(max_length=50, verbose_name='General Title')),
                ('working_days', models.CharField(max_length=30, verbose_name='Working Days')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('social_1', models.URLField(verbose_name='Social 1')),
                ('social_2', models.URLField(verbose_name='Social 2')),
                ('social_3', models.URLField(verbose_name='Social 3')),
                ('social_4', models.URLField(verbose_name='Social 4')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('path1', models.CharField(max_length=30, verbose_name='Path 1')),
                ('path2', models.CharField(max_length=30, verbose_name='Path 2')),
                ('path3', models.CharField(max_length=30, verbose_name='Path 3')),
                ('path4', models.CharField(max_length=30, verbose_name='Path 4')),
                ('path5', models.CharField(max_length=30, verbose_name='Path 5')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
    ]
