# Generated by Django 4.2.7 on 2023-11-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='social_1',
            new_name='social1',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='social_2',
            new_name='social2',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='social_3',
            new_name='social3',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='social_4',
            new_name='social4',
        ),
    ]
