# Generated by Django 4.2.7 on 2023-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_social_1_header_social1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='', verbose_name='Background')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtitle')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
                ('button_link', models.CharField(max_length=20, verbose_name='Button Link')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
