# Generated by Django 4.2.7 on 2023-11-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
                ('button_link', models.CharField(max_length=20, verbose_name='Button Link')),
            ],
            options={
                'verbose_name': 'Callback',
                'verbose_name_plural': 'Callback',
            },
        ),
    ]
