# Generated by Django 4.2.7 on 2023-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=40, verbose_name='Services Title')),
                ('colored_title1', models.CharField(max_length=40, verbose_name='Services Colored Title')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Services Subtitle')),
                ('title2', models.CharField(max_length=40, verbose_name='About Title')),
                ('colored_title2', models.CharField(max_length=40, verbose_name='About Colored Title')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='About Subtitle')),
                ('title3', models.CharField(max_length=40, verbose_name='Testomonials Title')),
                ('colored_title3', models.CharField(max_length=40, verbose_name='Testomonials Colored Title')),
                ('subtitle3', models.CharField(max_length=50, verbose_name='Testomonials Subtitle')),
                ('title4', models.CharField(max_length=40, verbose_name='Contact Title')),
                ('colored_title4', models.CharField(max_length=40, verbose_name='Contact Colored Title')),
                ('subtitle4', models.CharField(max_length=50, verbose_name='Contact Subtitle')),
            ],
        ),
    ]
