# Generated by Django 4.2.7 on 2023-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
            ],
        ),
    ]
