# Generated by Django 4.2.7 on 2023-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='', verbose_name='Background')),
                ('title', models.CharField(max_length=40, verbose_name='Contact Title')),
                ('colored_title', models.CharField(max_length=40, verbose_name='Contact Colored Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Contact Subtitle')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
            ],
        ),
    ]
