# Generated by Django 4.2.7 on 2023-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
