# Generated by Django 4.2.7 on 2023-11-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_footercontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercontact',
            options={'verbose_name': 'Footer Contact', 'verbose_name_plural': 'Footer Contact'},
        ),
    ]
