# Generated by Django 5.0.1 on 2024-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_footercontact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='path6',
            field=models.CharField(max_length=30, null=True, verbose_name='Path 6'),
        ),
    ]
