# Generated by Django 5.0.1 on 2024-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_header_path6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='subtitle1',
            field=models.CharField(max_length=100, verbose_name='Services Subtitle'),
        ),
    ]
