# Generated by Django 5.0.1 on 2024-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_title_subtitle1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='subtitle2',
            field=models.CharField(max_length=100, verbose_name='About Subtitle'),
        ),
        migrations.AlterField(
            model_name='title',
            name='subtitle3',
            field=models.CharField(max_length=100, verbose_name='Testomonials Subtitle'),
        ),
        migrations.AlterField(
            model_name='title',
            name='subtitle4',
            field=models.CharField(max_length=100, verbose_name='Contact Subtitle'),
        ),
    ]
