# Generated by Django 5.0.1 on 2024-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_title_subtitle2_alter_title_subtitle3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Subtitle'),
        ),
    ]
